### ISSUE TITLE
Capability "repository/osp:view" was not found!

### ISSUE THREAD

**Issue by ewallah** [UNEDLabs/moodle-repository_osp#1]
repository_osp
Capability "repository/osp:view" was not found! This has to be fixed in code.
line 389 of /lib/accesslib.php: call to debugging()
line 1121 of /repository/lib.php: call to has_capability()
line 296 of /repository/lib.php: call to repository::get_instances()
line 236 of /repository/lib.php: call to repository_type->update_options()
line 36 of /repository/osp/db/install.php: call to repository_type->create()
line 515 of /lib/upgradelib.php: call to xmldb_repository_osp_install()
line 1630 of /lib/upgradelib.php: call to upgrade_plugins()
line 433 of /admin/index.php: call to upgrade_noncore()

Moodle 2.9 new install

**Comment by Ravenink** [comment]
Hi,

We just did a new installation of the osp plugin in a fresh Moodle 2.9 and we weren’t able to replicate this problem. It got installed just fine.

Please double-check you have the access.php file inside the db directory in the osp plugin and that its content matches the one in Github. Capability osp:view is defined there.

De: ewallah [mailto:notifications@github.com] 
Enviado el: lunes, 15 de junio de 2015 21:58
Para: UNEDLabs/moodle-repository_osp
Asunto: [moodle-repository_osp] Capability "repository/osp:view" was not found! (#1)

repository_osp
Capability "repository/osp:view" was not found! This has to be fixed in code.
line 389 of /lib/accesslib.php: call to debugging()
line 1121 of /repository/lib.php: call to has_capability()
line 296 of /repository/lib.php: call to repository::get_instances()
line 236 of /repository/lib.php: call to repository_type->update_options()
line 36 of /repository/osp/db/install.php: call to repository_type->create()
line 515 of /lib/upgradelib.php: call to xmldb_repository_osp_install()
line 1630 of /lib/upgradelib.php: call to upgrade_plugins()
line 433 of /admin/index.php: call to upgrade_noncore()

Moodle 2.9 new install
